<a href="https://colab.research.google.com/github/iamatul1214/Tensorflow_Certification_Preparation/blob/main/00_fundamentals_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [2]:
## Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
## Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
##  Creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
## Check the dimensions of the vector
vector.ndim

1

In [6]:
## create a matrix ( it has more than 1 dimensions)

matrix = tf.constant([[10,5],[5,20]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [ 5, 20]], dtype=int32)>

In [7]:
## checking the dimensions of the matrix
matrix.ndim

2

In [8]:
## Create another matrix
another_matrix = tf.constant([[10.,5],
                              [3,2.],
                              [9,8.]], dtype = tf.float16)  ## specifying the datatype which we require  float16 will take lesser memory than float32 which is selected by default
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 3.,  2.],
       [ 9.,  8.]], dtype=float16)>

In [9]:
another_matrix = tf.constant([[10.,5],
                              [3,2.],
                              [9,8.]], dtype = tf.double)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[10.,  5.],
       [ 3.,  2.],
       [ 9.,  8.]])>

In [10]:
another_matrix.ndim

2

In [11]:
## Let's create a tensor

tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                       [12,13,5]],
                      [[18,19,20],
                     [10,11,12]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [12, 13,  5]],

       [[18, 19, 20],
        [10, 11, 12]]], dtype=int32)>

In [12]:
tensor.ndim

3

Scalar: A single number
Vector: A number with direction like wind, velocity
Matrix: A 2-dimensional array of numbers
Tensor: An n-dimensional array of numbers.
Note:
1. 0 dimensional tensor is scalar
2. 1 dimensional tensor is vector

### Creating tensors with tf.variable

In [13]:
## creating same tensors with tf.varible
changeble_tensor = tf.Variable([10,7])
unchangeble_tensor = tf.constant([10,7])
changeble_tensor,unchangeble_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [21]:
## Let's try to change one of the elements in our changeble tensor
changeble_tensor[0] = 4
changeble_tensor

TypeError: ignored

In [16]:
changeble_tensor[0].assign(4)
changeble_tensor[1].assign(2)
changeble_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 2], dtype=int32)>

In [20]:
## Let's try to change the unchangable tensor
unchangeble_tensor[0] = 7
unchangeble_tensor

TypeError: ignored

In [19]:
## Let's use assign method and check 
unchangeble_tensor[0].assign(8)
unchangeble_tensor


AttributeError: ignored

## creating random tensors
#### It can be utilized for initializing weights for NN

In [ ]:
## creating random tensors
random1 = tf.random.Generator.from_seed(43)
random1 = random1.normal(shape = (3,2))  ## for normal distribution
random1

In [ ]:
random2 = tf.random.Generator.from_seed(43)
random2 = random2.normal(shape=(3,2))
random2

In [ ]:
random1, random2, random1==random2

## Shuffle the order of elements in tensors
valuable when you want to shuffle the data for training


In [ ]:
not_shuffled = tf.constant([[10,7],
                            [4,5],
                            [3,9]])
not_shuffled

In [ ]:
## shuffling the non_shuffled tensor
tf.random.shuffle(not_shuffled)   

In [ ]:
tf.random.set_seed(43)  ## global level seed
tf.random.shuffle(not_shuffled,seed=43)    ## operational level seed

## Read through the Tensorflow documentation on random seed generation

In [ ]:
## other ways to create tensors
tf.ones(shape=(3,2), dtype='float32')

In [ ]:
tf.zeros(shape=(10,12), dtype='float16')

### Turn numpy arrays into tensorflow
The difference between numpy arrays and tensorflow tensors is that, tensors can be executed on GPU but numpy arrays can't.

In [ ]:
import numpy as np
numpy_array = np.arange(1,25, dtype=np.float32)
numpy_array

In [ ]:
from tensorflow.python.ops.gen_data_flow_ops import tensor_array_read
## converting into the tensors
tensor_from_np = tf.constant(numpy_array)
tensor_from_np

In [ ]:
tensor_B = tf.constant(numpy_array, shape=(2,4,3))
tensor_c = tf.constant(numpy_array, shape=(2,2,2,3))
tensor_B,tensor_c

## While dealing with tensors we should have following attributes of tensors known-->
### Shape
### Rank
### Axis or Dimension
### Size

In [25]:
## Let's create a rank 4 tensors ( rank 4 = a tensor with 4 dimensions)
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [27]:
## shape returns the shape of tensor, ndim returns total dimensions, size returns total elements in the tensor
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [28]:
## Get various attributes of a tensor
print(f"Data type of every element in the tensor = {rank_4_tensor.dtype}")
print(f"Total dimensions of the tensor = {rank_4_tensor.ndim}")
print(f"Shape of tensor = {rank_4_tensor.shape}")
print(f"Elements along the 0 axis = {rank_4_tensor[0]}")
print(f"Elements along the last axis = {rank_4_tensor[-1]}")
print(f"Total elements in the tensor = {tf.size(rank_4_tensor)}")

Data type of every element in the tensor = <dtype: 'float32'>
Total dimensions of the tensor = 4
Shape of tensor = (2, 3, 4, 5)
Elements along the 0 axis = [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
Elements along the last axis = [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
Total elements in the tensor = 120


## Tensors indexing
### Tensors can be indexed just like lists in python

In [24]:
## eg of list indexing in python
some_list = [1,2,3,4]
print(f"first two = {some_list[:2]}")
print(f"last two = {some_list[2:]}")
print(f"middle elements = {some_list[1:3]}")
print(f"reversed elements = {some_list[::-1]}")
print(f"printing list = {some_list[:]}")

first two = [1, 2]
last two = [3, 4]
middle elements = [2, 3]
reversed elements = [4, 3, 2, 1]
printing list = [1, 2, 3, 4]


In [ ]:
## Let's try same with tensors
rank_4_tensor[:2,:2,:2,:2]

In [29]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
# Get the first element from each dimension from each index except for the second last one
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [31]:
# Get the first element from each dimension from each index except for the second one
rank_4_tensor[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [32]:
# Get the first element from each dimension from each index except for the first one
rank_4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [33]:
# Get the first element from each dimension from each index except for the first and second one
rank_4_tensor[:,:,:1,:1]

<tf.Tensor: shape=(2, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]],


       [[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [34]:
## creating a rank 2 tensor means tensor with 2 dimensions
ranK_2_tensors = tf.constant([[10,7],
                              [6,8]])
ranK_2_tensors.ndim, ranK_2_tensors

(2, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 6,  8]], dtype=int32)>)

In [ ]:
## Get the last item of each of our rank 2 tensor
ranK_2_tensors[-1,-1]

In [37]:
## Get the last item of each row of our rank 2 tensor
ranK_2_tensors[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 8], dtype=int32)>

In [36]:
## changing the dimensions of the rank_2 tensor
tf.expand_dims(ranK_2_tensors, axis = -1)  # -1 means the last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 6],
        [ 8]]], dtype=int32)>

In [38]:
tf.expand_dims(ranK_2_tensors, axis = 0)  # 0 means the first axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 6,  8]]], dtype=int32)>

In [39]:
tf.expand_dims(ranK_2_tensors, axis=1)  # 1 means second axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 6,  8]]], dtype=int32)>

## Manipulating tensors
**Basic Operations**
`+`,`-`,`*`,`/` 

In [40]:
tensor = tf.constant([[10,7],[5,9]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [15, 19]], dtype=int32)>

In [41]:
## original tensor is still unchanged
tensor, tensor+12

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 5,  9]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[22, 19],
        [17, 21]], dtype=int32)>)

In [42]:
tensor - 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 2],
       [0, 4]], dtype=int32)>

In [43]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [10, 18]], dtype=int32)>

In [44]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [2.5, 4.5]])>

In [45]:
## We can use inbuilt tensorflow multiplication as well
tf.multiply(tensor,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [10, 18]], dtype=int32)>

## Matrix multiplication in tensors
**Rules**

1.The inner dimensions must match
2. The resulting matrix has the shape of outer dimension. 

In [46]:
## multiplyinng rank_2_tensor by itself using tensorflow and python
tf.matmul(ranK_2_tensors, ranK_2_tensors)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[142, 126],
       [108, 106]], dtype=int32)>

In [47]:
ranK_2_tensors @ ranK_2_tensors

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[142, 126],
       [108, 106]], dtype=int32)>

In [48]:
## Let's create two different matrices
tensor_1 = tf.constant([[1,2],
                        [3,4],
                        [5,6]])
tensor_2 = tf.constant([[7,8],[9,10],[11,12]])
tensor_1, tensor_2

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [49]:
## Now let's try to multiply 
tensor_1 @ tensor_2

InvalidArgumentError: ignored

In [50]:
tf.matmul(tensor_1, tensor_2)

InvalidArgumentError: ignored

In [51]:
## Now we will change the shape of any one of the matrixes to perform multiplication
tensor_1,tf.reshape(tensor_1, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [52]:
## multiplication using tensorflow
tf.matmul(tensor_1, tf.reshape(tensor_2, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [53]:
## multiplication using python
tensor_1 @ tf.reshape(tensor_2, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [54]:
## trying to change the shape of first matrix instead of second.
tf.matmul(tf.reshape(tensor_1, shape=(2,3)),tensor_2)  ## 2x3 vs 3x2 = 2x2 [outer dimensions]


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [55]:
tf.matmul(tensor_2, tf.reshape(tensor_1, shape=(2,3)))  ## 3x3 vs 2x3 = 3x3 [outer dimensions]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]], dtype=int32)>

In [56]:
## Let's see the transpose vs reshape
tensor_1, tf.reshape(tensor_1, shape=(2,3)),tf.transpose(tensor_1)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

In [57]:
  ## Multiplication using dot product
  ### Rmemeber transpose is actually the real thing to do, reshaping is marely reordering the elements but transpose changed the axis
  tf.tensordot(tf.transpose(tensor_1),tensor_2, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### Changing the datatype of tensor

In [58]:
B = tf.constant([[1.7,2.5]])
B.dtype

tf.float32

In [59]:
## changing it to float16
B = tf.cast(B,dtype = 'float16')
B.dtype

tf.float16

In [60]:
## With above operation if we have a tensor with million values then we can reduce the space to half and hence increasing the processing speed as well.

## Aggregate functions on tensors

In [61]:
## Absolute value--> it returns all the values on positive scale
C = tf.constant([1,-4,-8])
print(C)
tf.abs(C)

tf.Tensor([ 1 -4 -8], shape=(3,), dtype=int32)


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 8], dtype=int32)>

### Let's find the following
* Get the minimum
* Get the maximum
* Get the mean of the tensor
* Get sum of the tensor

In [64]:
## create a random tensor with values within 0 to 100 of size 50
import numpy as np
D = tf.constant(np.random.randint(0,100, size=50))
D

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([41, 53, 76, 61, 67, 41,  0, 82, 14, 58, 44, 63, 98, 44, 33, 87, 85,
       41, 16, 55, 36, 12, 55, 46, 52, 13, 51, 57, 88, 41, 57,  3, 76, 55,
       99, 24,  1, 90, 91, 83, 47, 24, 81, 80, 32, 87,  6, 64, 41, 89])>

In [65]:
D, D.shape,D.ndim

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([41, 53, 76, 61, 67, 41,  0, 82, 14, 58, 44, 63, 98, 44, 33, 87, 85,
        41, 16, 55, 36, 12, 55, 46, 52, 13, 51, 57, 88, 41, 57,  3, 76, 55,
        99, 24,  1, 90, 91, 83, 47, 24, 81, 80, 32, 87,  6, 64, 41, 89])>,
 TensorShape([50]),
 1)

In [66]:
## Finding minimum
print(tf.reduce_min(D))
print(np.min(D))


tf.Tensor(0, shape=(), dtype=int64)
0


In [67]:
## Finding maximum
print(tf.reduce_max(D))
print(np.max(D))

tf.Tensor(99, shape=(), dtype=int64)
99


In [68]:
## Finding mean
print(tf.reduce_mean(D))
print(np.mean(D))

tf.Tensor(52, shape=(), dtype=int64)
52.8


In [69]:
## Finding sum
print(tf.reduce_sum(D))
print(np.sum(D))

tf.Tensor(2640, shape=(), dtype=int64)
2640


In [70]:
## Finding variance
variance_numpy = (tf.reduce_sum(tf.abs(C - tf.reduce_mean(C))**2))/50
variance_numpy

<tf.Tensor: shape=(), dtype=float64, numpy=0.84>

In [71]:
## Finding standard deviation
sd = tf.sqrt(variance_numpy)
sd

<tf.Tensor: shape=(), dtype=float64, numpy=0.916515138991168>

In [ ]:
## Let's find variance and standrd deviation using tensorflow

In [72]:
tf.math.reduce_std(tf.cast(C, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=3.682>

In [73]:
tf.math.reduce_variance(tf.cast(C, dtype='float16'))

<tf.Tensor: shape=(), dtype=float16, numpy=13.555>

### Finding the positional maximum and minimum

In [74]:
tf.random.set_seed(40)
random_tensor = tf.random.uniform(shape=[50])
random_tensor


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.54513085, 0.7588961 , 0.8362565 , 0.39474642, 0.72001076,
       0.6402768 , 0.15894496, 0.57128036, 0.41122293, 0.18993318,
       0.2312665 , 0.7875649 , 0.18806243, 0.8033031 , 0.12747478,
       0.43258965, 0.98803484, 0.8451586 , 0.9797807 , 0.9952853 ,
       0.6283821 , 0.8643936 , 0.9500631 , 0.41532683, 0.388798  ,
       0.33959448, 0.36432612, 0.79217136, 0.90930283, 0.6459546 ,
       0.4547919 , 0.3669002 , 0.22951639, 0.54661405, 0.9371824 ,
       0.04014015, 0.82825315, 0.45409238, 0.943413  , 0.20978856,
       0.1274836 , 0.9666685 , 0.97015405, 0.568432  , 0.99477863,
       0.39956594, 0.3263564 , 0.61465824, 0.24279046, 0.03102553],
      dtype=float32)>

In [75]:
max_pos = tf.argmax(random_tensor)
max_pos

<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [76]:
random_tensor[max_pos]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9952853>

In [77]:
np.argmax(random_tensor)

19

In [78]:
## Min poistion
tf.argmin(random_tensor)


<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [79]:
random_tensor[tf.argmin(random_tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.031025529>

## Squeeze in tensorflow

#### It is used to remove all the 1 dimensions present in the tensor

In [80]:
tf.random.set_seed(42)
tensor = tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,1,50])
tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [81]:
## Now here we have too many 1 dimensions, we can remove them easily by tf.squeeze
squeezed = tf.squeeze(tensor)
squeezed, tensor, squeezed.shape, tensor.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.133187

## One hot encoded tensors

In [82]:
some_list = [0,1,2,3,4]
tf.one_hot(some_list, depth=4)


<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [83]:
tf.one_hot(some_list, depth = 5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [84]:
some_tensor = tf.constant([0,1,2,3,4])
tf.one_hot(some_tensor, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [86]:
## specifying custom values for one hot encoding
tf.one_hot(some_list, depth = 5, on_value="ON", off_value="OFF")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'ON', b'OFF', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'ON', b'OFF', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'ON', b'OFF', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'ON', b'OFF'],
       [b'OFF', b'OFF', b'OFF', b'OFF', b'ON']], dtype=object)>

## Squaring, log, Square root

In [87]:
new_tensor = tf.range(1,10)
new_tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [92]:
## squaring
tf.square(new_tensor)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [97]:
## Square root
tf.sqrt(new_tensor)

InvalidArgumentError: ignored

In [98]:
## changing the datatype of the tensor to float and trying
tf.sqrt(tf.cast(new_tensor, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [99]:
tf.math.log(tf.cast(new_tensor,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

## Numpy and tensors

In [101]:
numpy_array = np.array([4.,7.,2.])
numpy_array

array([4., 7., 2.])

In [102]:
tensor = tf.constant([4.,7.,2.])
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 7., 2.], dtype=float32)>

In [104]:
tensor_numpy = tf.constant(np.array([4.,6.5,8]))
tensor_numpy

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 6.5, 8. ])>

In [105]:
numpy_tensor = np.array(tf.constant([7,8,9]))
numpy_tensor

array([7, 8, 9], dtype=int32)

In [2]:
## Finding access to GPUs
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
!nvidia-smi

Sat Sep  3 08:38:14 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------